/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.mobileeng.abetterliving.model;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Data;

/**
 * @author Raphael Fuchs
 */

@Data
@Entity
@Table(name = "LISTS")
public class Lists {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long listID;

    @Basic
    private String type;

    @Basic
    private String name;

    @ManyToOne
    private Users user;

    /*public Long getListID() {
        return this.ListID;
    }

    public void setListID(Long ListID) {
        this.ListID = ListID;
    }

    public String getType() {
        return this.Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public String getName() {
        return this.Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Users getUser() {
        return this.user;
    }

    public void setUser(Users user) {
        this.user = user;
    }*/

}